name: bayer
description: BAYEUR - Gestion des logements et des locations
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Fonts
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  flutter_svg_provider: ^1.0.7
      # ðŸ”¥ Version compatible AGP 8.7.x
  toggle_switch: ^2.3.0

  # Networking & HTTP
  http: ^1.2.2
  dio: ^5.4.2
  connectivity_plus: ^6.1.1
  network_info_plus: ^6.0.0

  # State & Navigation
  get: ^4.6.5
  shared_preferences: ^2.2.2
  intl: ^0.20.1
  uuid: ^4.5.1

  # File handling
  path: ^1.9.0
  path_provider: ^2.1.3
  image_picker: ^1.0.8
  file_saver: ^0.3.1
  open_file: ^3.5.10
  pdf: ^3.11.3
  printing: ^5.12.0

  # Animations & Loading
  lottie: ^3.1.2
  loading_indicator: ^3.1.1
  flutter_easyloading: ^3.0.5
  toastification: ^3.0.3

  # Charts
  fl_chart: ^0.69.0
  syncfusion_flutter_charts: ^30.1.39

  # Responsiveness
  responsive_builder: ^0.7.1

  # Security
  crypto: ^3.0.6
  sqflite: ^2.3.3+1
  data_table_2: ^2.6.0
  logger: ^2.1.0
  sqflite_common_ffi: ^2.3.3+1
  icons_plus: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animation/
    - assets/icons/

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  macos:
    generate: true
  windows:
    generate: true
  linux:
    generate: true
  image_path: "assets/images/logo.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  branding: assets/images/logo.png
  fullscreen: false
  android: true
  ios: true
  web: false
